#Spring boot application.yml


spring:
  #profiles : dev
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    #jdbc:mysql://localhost:3306/cookbook?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    url: jdbc:oracle:thin:@localhost:1521:iflytek
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  # transaction manager
  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager


mybatis:
  type-aliases-package: com.sunyu.hdfs
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:com/sunyu/hdfs/mapping/*.xml
server:
  port: 8080
  undertow:
     accesslog:
      enabled: true
      dir: ../logs