#Spring boot application.yml


spring:
  data:
    hdfs:
      defaultFS: hdfs://192.168.248.128:9000
      impl: org.apache.hadoop.hdfs.DistributedFileSystem



server:
  port: 8080
  undertow:
     accesslog:
      enabled: true
      dir: ../logs